import processToCheckOut from "../support/pageObjects/processToCheckOut"

describe('Process to Checkout on Magento', () => {
    beforeEach(() => {
        cy.visit('https://magento.softwaretestingboard.com/') //Access URL Magento
    })
    it.skipp('First time checkout Product', () => { //Note jika belum pernah melakukan checkout dan ada product di chart
        ProcessToCheckOut.SignIn()
        ProcessToCheckOut.InputEmail('montanagurning913@gmail.com')
        ProcessToCheckOut.InputPass('@Montanasanbercode50')
        ProcessToCheckOut.BtnLogin()
        cy.wait(6000)
        ProcessToCheckOut.BtnChart()
        ProcessToCheckOut.BtnCheckout1()
        cy.wait(6000)
        ProcessToCheckOut.Fill_Comp('PT. Bank Central Asia, Tbk.')
        ProcessToCheckOut.Fill_Add1('Jl. Agung Kurniawan')
        ProcessToCheckOut.Fill_Add2('xxxxxxxxx')
        ProcessToCheckOut.Fill_Add3('yyyyyyyyy')
        ProcessToCheckOut.Fill_City('Jakarta Selatan')
        ProcessToCheckOut.Fill_Reg1('2')
        ProcessToCheckOut.Fill_Post('22384')
        ProcessToCheckOut.Fill_Reg2('2')
        ProcessToCheckOut.Fill_Phone('081260021225')
        ProcessToCheckOut.Radio_Btn1()
        ProcessToCheckOut.Next_Btn()
        cy.wait(6000)
        ProcessToCheckOut.Pay_Btn()
        cy.contains('Thank you for your purchase!')
    })
    it('Have checked out before', () => { //Note jika sudah pernah melakukan checkout dan ada product di chart
        ProcessToCheckOut.SignIn()
        ProcessToCheckOut.InputEmail('montanagurning913@gmail.com')
        ProcessToCheckOut.InputPass('@Montanasanbercode50')
        ProcessToCheckOut.BtnLogin()
        cy.wait(6000)
        ProcessToCheckOut.BtnChart()
        ProcessToCheckOut.BtnCheckout1()
        cy.wait(10000)
        ProcessToCheckOut.Radio_Btn1()
        ProcessToCheckOut.Next_Btn()
        cy.wait(10000)
        ProcessToCheckOut.Pay_Btn()
        cy.contains('Thank you for your purchase!')
    })
})
